# version: 0.2

# phases:
#   install:
#     commands:
#       - npm install
#   build:
#     commands:
#       - npm run build

# artifacts:
#   files:
#     - '**/*'
#   base-directory: public
#   discard-paths: yes

version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed. Listing contents of the project directory:"
      - ls -la
      - echo "Listing contents of the public directory:"
      - ls -la public
      - aws s3 sync public/ s3://gastbyweb-dep/ --acl public-read

artifacts:
  files:
    - '**/*'
  base-directory: public
  discard-paths: yes
